### ISSUE TITLE
Tool misses buckets open to authUsers

### ISSUE THREAD

**Issue by sa7mon** [koenrh/s3enum#11]
Hi there,

First of all, nice tool! Wordlist and suffix list parsing is something I want to add to my own s3 scanner.

Just in case you don't know already, doing a DNS check if a bucket is accessible will only tell you if that bucket is accessible for anonymous users. AWS lets you set permissions on buckets for both anonymous users and those with an AWS account, so if a bucket is not accessible for anon users but is accessible for authenticated users, the tool will return that the bucket is not open.

More information can be found here: https://docs.aws.amazon.com/AmazonS3/latest/user-guide/set-bucket-permissions.html

**Comment by koenrh** [comment]
Yes, you are correct! You would use this tool in the recon phase to discover the organisation's S3 buckets. It does indeed not do any permission checking, you would need to use another tool for that (or your own).

The (original) main goal was to have fast tool to enumerate buckets, i.e. something faster than relying on HTTP calls.
