### ISSUE TITLE
multiple words and performance considerations

### ISSUE THREAD

**Issue by unl1k3ly** [koenrh/s3enum#19]
Hi Mate,

Awesome project! Thank you.

Wondering, would be possible to allow it running multiple words like, company1, company2 into a single run ?

Also, there seems to be so slow resolving... perhaps it comes down to a fact that its asking Google's DNS rather than use that one from resolv.conf ? Am I right ? Is there something we can do to increase its execution ? Like, gobuster for example...

Cheers

**Comment by koenrh** [comment]
>Wondering, would be possible to allow it running multiple words like, company1, company2 into a single run ?

Good idea! I'll take that as a feature request.

>Also, there seems to be so slow resolving... perhaps it comes down to a fact that its asking Google's DNS rather than use that one from resolv.conf ? Am I right ? Is there something we can do to increase its execution ? Like, gobuster for example...

At the very least it should be possible to specify your own resolver:

https://github.com/koenrh/s3enum/blob/9bde6e7ef4728d25dc80f948d8112c04969d9329/bucket_checker.go#L41-L42

I guess it should also be fairly straightforward to read from `/etc/resolv.conf` using [`ClientConfigFromFile(resolvconf string)`](https://godoc.org/github.com/miekg/dns#ClientConfigFromFile).

**Comment by unl1k3ly** [comment]
Well, that would be the best! Google normally slow things down when doing mass requests!

I wish I knew some go so I could help you out :(

Thanks heaps mate.

Cheers

**Comment by koenrh** [comment]
Implemented in #20 and #21.

I'll merge it into `master` later today after some testing.

**Comment by koenrh** [comment]
All merged. It now picks the top name server from `/etc/resolv.conf`, and supports multiple name arguments. Let me know if you see issues.

**Comment by unl1k3ly** [comment]
Thanks mate !
