### ISSUE TITLE
Import cycle not allowed 

### ISSUE THREAD

**Issue by joeldeleep** [koenrh/s3enum#32]
I tried to install using the below command 
go get -u github.com/koenrh/s3enum 

and it shows following error

```bash
import cycle not allowed
package github.com/koenrh/s3enum
	imports bufio
	imports bytes
	imports errors
	imports runtime
	imports internal/bytealg
	imports internal/cpu
	imports runtime
```

**Comment by koenrh** [comment]
Hi @joeldeleep, could you share your GOPATH (`echo $GOPATH`) and Go version (`go version`)?

**Comment by joeldeleep** [comment]
my go path is : /home/user/go
go version is : go version go1.6.2 linux/amd64

**Comment by koenrh** [comment]
That version of Go is pretty old. Anything older than Go 1.10 is not supported anymore. Could you try to remove the package (`go clean -i github.com/koenrh/s3enum...`), upgrade to a recent version of Go (1.11 or 1.12), and then try again?
