### ISSUE TITLE
why no us-east-1?

### ISSUE THREAD

**Issue by hehnope** [koenrh/s3enum#54]
❓

**Comment by koenrh** [comment]
S3 buckets located in regions outside of the us-east-1 region give a different DNS response when addressed with the global S3 DNS suffix (`s3.amazonaws.com`). This is what allows the tool to determine whether an S3 bucket exists or not for all buckets, except the buckets located in the us-east-1 region. For us-east-1 buckets the DNS response is the same for both existing and non-existing buckets.
